# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.setEnabled(True)
        Main.resize(281, 266)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Main.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txtUrl = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUrl.setObjectName("txtUrl")
        self.verticalLayout_2.addWidget(self.txtUrl)
        self.btnFetch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFetch.setObjectName("btnFetch")
        self.verticalLayout_2.addWidget(self.btnFetch)
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setWordWrap(True)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle)
        self.selectFormat = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selectFormat.setObjectName("selectFormat")
        self.verticalLayout_2.addWidget(self.selectFormat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDownload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDownload.setObjectName("btnDownload")
        self.horizontalLayout.addWidget(self.btnDownload)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.lblDest = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDest.setObjectName("lblDest")
        self.verticalLayout_2.addWidget(self.lblDest)
        self.txtDest = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtDest.setEnabled(False)
        self.txtDest.setObjectName("txtDest")
        self.verticalLayout_2.addWidget(self.txtDest)
        self.btnBrowse = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.verticalLayout_2.addWidget(self.btnBrowse)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        Main.setCentralWidget(self.centralwidget)
        self.statusBar1 = QtWidgets.QStatusBar(parent=Main)
        self.statusBar1.setObjectName("statusBar1")
        Main.setStatusBar(self.statusBar1)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Youtube DL"))
        self.btnFetch.setText(_translate("Main", "Fetch"))
        self.lblTitle.setText(_translate("Main", "Title"))
        self.btnDownload.setText(_translate("Main", "Download"))
        self.lblDest.setText(_translate("Main", "Destination"))
        self.btnBrowse.setText(_translate("Main", "Browse"))
